### obtener todos los characters(get all)
GET http://localhost:3000/api/characters
### obtener un character(get one)
GET http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo character
POST http://localhost:3000/api/characters
Content-Type: application/json

{
  "name":"Atila",
  "characterClass":"warrior",
  "items":["bow","arrow"],
  "attack": 10,
  "mana": 10,
  "hp": 10,
  "level": 1
} 


### modificar un character (PUT  - recurso completo e idempotente)
PUT http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "name":"Atilax",
  "characterClass":"warriorx",
  "items":["bowx","arrowx"],
  "attack": 102,
  "mana": 103,
  "hp": 101,
  "level": 11
} 


### modificar un character (PATCH  - recurso parcial)
PATCH http://localhost:3000/api/characters/9c20847e-af61-458f-8912-0f0efad815ab
Content-Type: application/json

{
  "name":"Atil",
  "characterClass":"war",
  "items":["CORAZON"],
  "level": 12
} 

### borrar un character
DELETE http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad