### Obtener todos los publishers(GET ALL)
GET http://localhost:3000/api/publishers
### Obtener un publisher(GET ONE)
GET http://localhost:3000/api/publishers/3

### Crear un nuevo publisher
POST http://localhost:3000/api/publishers/create
Content-Type: application/json


 {
  "publishername": "Hi rez",
  "foundation_date": "2024-04-16T00:04:12.275Z",
  "status": true,
  "creationtimestamp": "2024-04-16T00:04:12.275Z",
  "creationuser": "Alex"
}


### Modificar un publisher (PUT  - recurso completo e idempotente)
PUT http://localhost:3000/api/publishers/9
Content-Type: application/json

 {
  "publishername": "Ubisofttttttt",
  "dissolution_date": "2024-04-16T00:04:12.275Z",
  "status": true
}

### Borrar un publisher
DELETE http://localhost:3000/api/publishers/2