### obtener todos los hostings(get all)
GET http://localhost:3000/api/hostings/findall
### obtener un hosting(get one)
GET http://localhost:3000/api/hostings/1

### crear un nuevo hosting
POST http://localhost:3000/api/hostings/create
Content-Type: application/json

 {
  "name": "nacho_server_plus",
  "creationuser": "nacho",
  "creationtimestamp": "2024-04-16T00:04:12.275Z",
  "status": true
}


### modificar un hosting 
PUT http://localhost:3000/api/hostings/2
Content-Type: application/json

{
  "name": "Natoram_server_plus_max",
  "status": true
}

### borrar un hosting
DELETE http://localhost:3000/api/hostings/1