### Obtener todos los categorias

GET http://localhost:3000/api/categories

### Obtener un categorias

GET http://localhost:3000/api/categories/3

### Crear un categorias

POST http://localhost:3000/api/categories/create
Content-Type: application/json

{
    "description": "Categoria de Prueba",
    "creationtimestamp": "2024-04-16T00:04:12.275Z",
    "creationuser": "Alex"
}

### Modificar un categorias / cambio total
PUT http://localhost:3000/api/categories/3
Content-Type: application/json

{
    "description": "Modificacion total",
    "modificationuser": "Alex"
}

### Borrar un categorias

DELETE http://localhost:3000/api/categories/1