### Obtener todos los categorias

GET http://localhost:3000/api/categories

### Obtener un categorias

GET http://localhost:3000/api/categories/1

### Crear un categorias

POST http://localhost:3000/api/categories

Content-TypeL application/json

{
    "id": 1,
    "description": "Categoria de Prueba",
    "creationtimestamp": "2024-04-14 15:30:00.000",
    "modificationtimestamp": "2024-04-14 15:30:00.000"
}

### Modificar un categorias / cambio total
PUT http://localhost:3000/api/categories/1
Content-Type: application/json

{
    "description": "Modificacion total de categorias de prueba",
    "creationtimestamp": "2024-04-14 15:30:00.000",
    "modificationtimestamp": "2024-04-14 15:30:00.000",
    "modificationuser": "2024-04-14 15:30:00.000"
}

### Borrar un categorias

DELETE http://localhost:3000/api/categories/1