### Obtener todos los developers(GET ALL)
GET http://localhost:3000/api/developers
### Obtener un developers(GET ONE)
GET http://localhost:3000/api/developers/1

### Crear un nuevo developers
POST http://localhost:3000/api/developers
Content-Type: application/json


 {
  "developername": "Hi rez",
  "foundation_date": "2024-04-16T00:04:12.275Z",
  "dissolution_date": "2024-04-16T00:04:12.275Z",
  "status": true,
  "creationtimestamp": "2024-04-16T00:04:12.275Z",
  "creationuser": "Alex"
}


### Modificar un developers (PUT  - recurso completo e idempotente)
PUT http://localhost:3000/api/developers/1
Content-Type: application/json

 {
  "developername": "Ubisofttttttt",
  "dissolution_date": "2024-04-16T00:04:12.275Z",
  "status": true,
  "modificationtimestamp": "2024-04-16T00:04:12.275Z",
  "modificationuser": "Mauro"
}

### Borrar un developers
DELETE http://localhost:3000/api/developers/1