### Obtener todos los foros

GET http://localhost:3000/api/foros

### Obtener un foro

GET http://localhost:3000/api/foros/1

### Crear un foro

POST http://localhost:3000/api/foros

Content-TypeL application/json

{
    "id": 1,
    "id_user": 1,
    "description": "Foro de Prueba",
    "multimedia": "a02b91bc-3769-4221-beb1-d7a3aeba7dad",
    "creationtimestamp": "2024-04-14 15:30:00.000",
    "modificationtimestamp": "2024-04-14 15:30:00.000"
}

### Modificar un foro / cambio total
PUT http://localhost:3000/api/foros/1
Content-Type: application/json

{
    "id": "1",
    "id_user": "2",
    "description": "Modificacion total de foro de prueba",
    "multimedia": "a02b91bc-3769-4221-beb1-d7a3aeba7dad",
    "creationtimestamp": "2024-04-14 15:30:00.000",
    "modificationtimestamp": "2024-04-14 15:30:00.000"
}

### Modificar un foro / cambio parcial
PATCH http://localhost:3000/api/foros/1
Content-Type: application/json

{
    "id": 1,
    "id_user": 3,
    "description": "Modificacion parcial de foro de prueba",
    "multimedia": "a02b91bc-3769-4221-beb1-d7a3aeba7dad"
}

### Borrar un foro

DELETE http://localhost:3000/api/foros/1